name: PHPMD check

on:
  pull_request_target:
    types: [opened]

jobs:
  phpcs:
      name: PHPMD
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: PHPMD check
          uses: pmagentur/pm_php_md@master
          with:
            files: '.'
            renderers: 'xml'
            only_changed_files: 'true'
